spring.application.name=public-housing-mvp

spring.datasource.url=jdbc:mysql://localhost:3306/housing_demo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

security.jwt.secret=change-me-to-a-long-random-secret-key-for-hs256-signing
security.jwt.expiration-hours=12

external.lh.service-key=761957fc776455575e34c356bd90b6438d0c0646a4237df1ebaa4bed59ef9ce9
external.myhome.service-key=761957fc776455575e34c356bd90b6438d0c0646a4237df1ebaa4bed59ef9ce9
external.rtms.service-key=761957fc776455575e34c356bd90b6438d0c0646a4237df1ebaa4bed59ef9ce9
