spring.application.name=subscription
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration-hours=12

openai.api-key=${OPENAI_API_KEY}
openai.model=gpt-4o-mini
openai.base-url=https://api.openai.com/v1

external.lh.service-key=761957fc776455575e34c356bd90b6438d0c0646a4237df1ebaa4bed59ef9ce9

spring.task.scheduling.pool.size=2